azs:
- name: z1
  cloud_properties:
    zone: ru-central1-a
- name: z2
  cloud_properties:
    zone: ru-central1-b
- name: z3
  cloud_properties:
    zone: ru-central1-c

vm_types:
- name: default
  cloud_properties:
    cpu: 2
    ram: 2048
    disk: 12288
- name: large
  cloud_properties:
    cpu: 2
    ram: 4096
    disk: 12288

disk_types:
- name: default
  disk_size: 3000
- name: large
  disk_size: 50_000

networks:
- name: default
  type: manual
  subnets:
  - range: 10.0.0.0/23
    gateway: 10.0.0.1
    reserved: [10.0.0.1-10.0.0.50]
    az: z1
    dns: [8.8.8.8,8.8.4.4]
    cloud_properties:
      name: infra

compilation:
  workers: 5
  reuse_compilation_vms: true
  az: z1
  vm_type: large
  network: default

