bosh create-env bosh-deployment/bosh.yml \
                                          --state=xxx-state.json \
                                          --vars-store=xxx-creds.yml \
                                          -o bosh-yandex-cpi-release/opfiles/yandex.opfile.yml \
                                          -v director_name=bosh-1 \
                                          -v internal_ip=10.0.0.6 \
                                          -v internal_cidr=10.0.0.0/24 \
                                          -v internal_gw=10.0.0.1 \
					  -v token='<TOKEN>' \
	 				  -v cloud_name='<CLOUD NAME>'\
				          -v folder_name='<FOLDER NAME>' \
					  -v robot_account='<ROBOT_ACCOUNT>' \
					  -v zone='<ZONE>' \
					  -v network='<NETWORK>' \
				          -v subnetwork='<SUBNET>'
